### ISSUE TITLE
Error while tring to install nuget package on xamarin forms

### ISSUE THREAD

**Issue by egarim** [dreamfactorysoftware/.net-sdk#1]
Hi I'm no able to install the neuget package on xamarin forms android or iOS project, I'm currently using  a shared project and xamarin forms 1.4

Attempting to resolve dependency 'Unirest-API (≥ 1.0.6.8)'.
Attempting to resolve dependency 'Microsoft.Bcl (≥ 1.1.9)'.
Attempting to resolve dependency 'Microsoft.Bcl.Build (≥ 1.0.14)'.
Attempting to resolve dependency 'Microsoft.Net.Http (≥ 2.2.28)'.
Attempting to resolve dependency 'Newtonsoft.Json (≥ 6.0.8)'.
Installing 'Microsoft.Net.Http 2.2.28'.
Successfully installed 'Microsoft.Net.Http 2.2.28'.
Installing 'Newtonsoft.Json 6.0.8'.
Successfully installed 'Newtonsoft.Json 6.0.8'.
'Unirest-API 1.0.6.8' already installed.
'DreamFactoryNet 1.0.2' already installed.
Adding 'Microsoft.Net.Http 2.2.28' to Tinker.PanteraFramework.Forms.Droid.
Successfully added 'Microsoft.Net.Http 2.2.28' to Tinker.PanteraFramework.Forms.Droid.
Adding 'Newtonsoft.Json 6.0.8' to Tinker.PanteraFramework.Forms.Droid.
Successfully added 'Newtonsoft.Json 6.0.8' to Tinker.PanteraFramework.Forms.Droid.
Executing script file 'C:\Users\Joche\documents\visual studio 2013\Projects\Tinker.PanteraFramework\packages\Newtonsoft.Json.6.0.8\tools\install.ps1'.
Adding 'Unirest-API 1.0.6.8' to Tinker.PanteraFramework.Forms.Droid.
Successfully added 'Unirest-API 1.0.6.8' to Tinker.PanteraFramework.Forms.Droid.
Adding 'DreamFactoryNet 1.0.2' to Tinker.PanteraFramework.Forms.Droid.
Uninstalling 'Newtonsoft.Json 6.0.8'.
Successfully uninstalled 'Newtonsoft.Json 6.0.8'.
Uninstalling 'Microsoft.Net.Http 2.2.28'.
Successfully uninstalled 'Microsoft.Net.Http 2.2.28'.
Install failed. Rolling back...
Could not install package 'DreamFactoryNet 1.0.2'. You are trying to install this package into a project that targets 'MonoAndroid,Version=v5.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by egarim** [comment]
Hi any news on this issue? I'm really looking forward to use the dream factory sdk with my xamarin projects

**Comment by makosovic** [comment]
Hi Jose,
I have published new nuget package today. You can find it on nuget https://www.nuget.org/packages/DreamFactoryNet/2.0.0. It does however target version 2.0 of DreamFactory that is currently in beta so you will want to look into that if you are not already using it. 
Let me know if that resolved your issue.
Regards

**Comment by egarim** [comment]
Hi Marko
I just download the package and it worked great, any advice on where I can
get dream factory 2? I'm using the version that is publish in bitnami which
is 1.9.4-3. if I can upgrade my current version it would be great.

BTW: I'm great fan of dream factory great job

Regard
Jose Manuel Ojeda

On Wed, Sep 23, 2015 at 2:19 PM, Marko Kosović notifications@github.com
wrote:

> Hi Jose,
> I have published new nuget package today. You can find it on nuget
> https://www.nuget.org/packages/DreamFactoryNet/2.0.0. It does however
> target version 2.0 of DreamFactory that is currently in beta so you will
> want to look into that if you are not already using it.
> Let me know if that resolved your issue.
> Regards
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/dreamfactorysoftware/.net-sdk/issues/1#issuecomment-142747073
> .

## 

Regards
Jose Manuel Ojeda

Skype:Jose.Manuel.Ojeda
GoogleTalk:joche.ojeda@bitframeworks.com
Cellphone: 503 79235612
QQ:2492739188

**Comment by makosovic** [comment]
Unfortunately there is no upgrade path for version 2.0, you will have to export your apps and import them into a clean v2.0 install. You can find the installers on the bitnami page, make sure you explore 'other options', there you will find DreamFactory 2.0.beta-2. I'm going to go ahead and close this issue, let me know if you have any other questions. Also you should check out http://community.dreamfactory.com/ there is a lot of useful info that might help.
