### ISSUE TITLE
is there a way to create a related query using the sdk, just as the query ben show in this tutorial

### ISSUE THREAD

**Issue by egarim** [dreamfactorysoftware/.net-sdk#11]
is there a way to create a related query using the sdk?, just as the query Ben show in this tutorial

http://blog.dreamfactory.com/blog/bid/316052/Demo-How-to-Make-Relationship-Queries-with-DreamFactory-s-REST-API

**Comment by makosovic** [comment]
Of course there is, you should check out the AddressBook Demo https://github.com/dreamfactorysoftware/.net-sdk/blob/master/DreamFactory.AddressBook/Controllers/ContactController.cs.

Regards
Marko
