### ISSUE TITLE
what would be the correct way to represent a many to many relationship using the databaseapi

### ISSUE THREAD

**Issue by egarim** [dreamfactorysoftware/.net-sdk#12]
Hi I'm creating a mobile client for an existing system, in the system there is a many to many relationship.

so far my solution is to query each table and them join the result in code or somehow  send the api the text of a join query,I would prefer the later (the join query). any example on how achieve my goal?

**Comment by makosovic** [comment]
You have to explore the TableSchema, and then join by using `related` and the related relationship names.

Regards
Marko
