### ISSUE TITLE
Error when query related data

### ISSUE THREAD

**Issue by egarim** [dreamfactorysoftware/.net-sdk#13]
Hi Marko, I try to query the related data but I got an error in the following scenarios

-.net code
 SqlQuery tquery = new SqlQuery { Filter = "GCRecord is null", Order = "Oid", Fields = "*",Related= "imagedetail_by_PostBase", IncludeCount = true };
            DatabaseResourceWrapper <PostObject> TResult = await databaseApi.GetRecordsAsync<PostObject>("postbase", tquery);

-error on .net
400 - Invalid relationship 'imagedetail_by_postbase' requested

if I try to get the related data of a many to many I got the following error

-.net code
 SqlQuery tquery = new SqlQuery { Filter = "GCRecord is null", Order = "Oid", Fields = "*",Related= "tag_by_tagtags_postbasepostbases", IncludeCount = true };
            DatabaseResourceWrapper <PostObject> TResult = await databaseApi.GetRecordsAsync<PostObject>("postbase", tquery);

-error on .net
500 - The Response content must be a string or object implementing __toString(), &quot;boolean&quot; given.

if i try to do the same on dream factory side I get this (this is the request http://localhost:80/api/v2/LaGuiaApi/_table/postbase?related=imagedetail_by_PostBase)

The Response content must be a string or object implementing __toString(), &quot;boolean&quot; given.",

here I include the schema of the table postbase
[PostBase.pdf](https://github.com/dreamfactorysoftware/.net-sdk/files/34686/PostBase.pdf)

**Comment by makosovic** [comment]
Regarding the 400 error, I suspect it might be the relationship name because in your query PostBase is pascal cased and in the error it is lower cased. Can you record the HTTP request being sent to the DreamFactory API with fiddler and verify that the relationship name is sent as you have requested it because if it is not it might be something in the SDK, otherwise it is in the DreamFactory API that is causing the error.

As for the 500 error. I haven't came across it myself ever, perhaps it would be best if you posted that part of the issue to the community forum (http://community.dreamfactory.com/).

Regards
Marko

**Comment by egarim** [comment]
Hi Marko
in fact the request sent is all in lower case, so I guess is something in the sdk, here is a copy of the request I got from fiddler

GET /api/v2/LaGuiaApi/_table/postbase?filter=gcrecord%20is%20null&order=oid&fields=*&related=imagedetail_by_postbase&include_count=true HTTP/1.1
X-Folder-Name: LaGuia
X-DreamFactory-Api-Key: 325f19658582166a1aedda950c7e5c4c252f121ddf67637b2c15832a26ee8ca7
Accept: application/json
X-DreamFactory-Session-Token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjEsInVzZXJfaWQiOjEsImVtYWlsIjoiam9jaGUub2plZGFAYml0ZnJhbWV3b3Jrcy5jb20iLCJmb3JldmVyIjpmYWxzZSwiaXNzIjoiaHR0cDpcL1wvbXNpXC9hcGlcL3YyXC9zeXN0ZW1cL2FkbWluXC9zZXNzaW9uIiwiaWF0IjoiMTQ0NzgwODMyOSIsImV4cCI6IjE0NDc4MTE5MjkiLCJuYmYiOiIxNDQ3ODA4MzI5IiwianRpIjoiNDg2Y2E5MWZhYjg2MzZlMTQ3ZGI3OWM5ZjYzZTVlM2YifQ.QTOIB6KZOM0bIpHROmGrhjZkUU8xn8hR8EHG7VQAg24
user-agent: unirest-net/1.0
Host: msi

**Comment by makosovic** [comment]
Which release of SDK / nuget package are you using? Make sure you are using the latest https://github.com/dreamfactorysoftware/.net-sdk/releases/tag/2.0.3 that has a couple of fixes regarding the serialization.

Regards
Marko

**Comment by egarim** [comment]
this is the version I'm using 2.0.3.37549

**Comment by makosovic** [comment]
Ok, thanks for the details. I'll look into it further.

**Comment by makosovic** [comment]
I believe I fixed it with [this changeset](https://github.com/dreamfactorysoftware/.net-sdk/commit/1b7dce4609a057be2c5fe024447ae0d81e9e62b7). It's on hotfix branch if you can make use of it. I'll merge it and release it as soon as I'm able to test it thoroughly.

Regards
Marko

**Comment by makosovic** [comment]
Fixed with the [latest release](https://github.com/dreamfactorysoftware/.net-sdk/releases/tag/2.0.4).
