### ISSUE TITLE
Database Api Transaction

### ISSUE THREAD

**Issue by egarim** [dreamfactorysoftware/.net-sdk#14]
Hi, I have a master detail scenario where I would like to save all master and detail records on a single transaction , does the sdk provide this functionality?

Currently I'm using POCO objects and they are not related to each other

If there is not possible to use transactions, I think use a store procedure to do the CRUD on a master detail object would be ok. is there a sample to call store procedures with parameters?

**Comment by makosovic** [comment]
The DreamFactory SDK does not provide support for transactions, however your instinct to use the stored procedure is spot on. Here is an example for calling the stored procedure with parameters:

``` csharp
IRestContext context = new RestContext("http://localhost:8080");
IDatabaseApi databaseApi = context.Factory.CreateDatabaseApi("my_db_service_name");

StoreProcParamsBuilder builder = new StoreProcParamsBuilder();
builder.WithInParam("id", 1);
ResultDTO result = await databaseApi.CallStoredProcAsync<ResultDTO>("my_stored_proc_with_param", builder.Build());
```
