### ISSUE TITLE
call a custom script service from the sdk

### ISSUE THREAD

**Issue by egarim** [dreamfactorysoftware/.net-sdk#16]
Hi, is there a way to call a customs script service from the sdk? I need to create a service just as the one shown in here

http://wiki.dreamfactory.com/DreamFactory/Tutorials/V8_custom_scripting_service

so I want to know if  i should call it using an http client or does the sdk have an api for that?

**Comment by makosovic** [comment]
It is not possible to create a service or invoke custom service scripts using the SDK at this moment.

Regards
Marko
