### ISSUE TITLE
implement transactions

### ISSUE THREAD

**Issue by egarim** [dreamfactorysoftware/.net-sdk#18]
Hi i think the sdk will be more useful if you implement transactions for the db api, right now the only way to have a transaction behavior is a stored procedure

**Comment by makosovic** [comment]
AFAIK DreamFactory db service API does not support transactions at this moment, which means the implementation would be complex, kinda hacky and tied to .NET SDK specifically. Perhaps someone in the community forum could tell you if there are future plans to implement transactions in the db service API.

Regards
Marko

**Comment by makosovic** [comment]
There is no transaction support on the road map because there are doubts whether it would be possible to implement transactions with state less requests.
