### ISSUE TITLE
NoSQL example

### ISSUE THREAD

**Issue by egarim** [dreamfactorysoftware/.net-sdk#19]
Hi would you be so kind to include a no example may be couch or mongo, we are trying to figure out if we will use relation database or nosql database in our next project and a sample from you would really help us to decide

**Comment by makosovic** [comment]
What exactly do you mean by example? DatabaseApi in the SDK is actually a facade for any db service in the DF that in turn is an abstraction of different data sources, so the usage is pretty much the same. Perhaps limited partially by DF or 3rd party library used to connect to different sources.

**Comment by egarim** [comment]
well I mean for example mongo db support nested objects for example this master detail example

var purchase_order = { 
  _id: 1
  title: ‘Purchase order 1’,
  total: 10.50,
  line_items: [ 
    { sku: ‘a’, quantity: 1, price: 10.50 }
  ]
} 

so in the example I just want to know how to represent a master detail object scenario for the C.R.U.D operations

**Comment by makosovic** [comment]
It's up to you basically. MongoDB as you said supports nested objects as it is a document store and would certainly simplify any master detail object scenario. You wouldn't have the need to have multiple tables and wouldn't have to deal with related fields which I would assume are not supported.

**Comment by egarim** [comment]
so I can create a nested POCO object and just save it to the db?

**Comment by makosovic** [comment]
I would belive so.
