### ISSUE TITLE
IDatabaseApi create table relations example

### ISSUE THREAD

**Issue by egarim** [dreamfactorysoftware/.net-sdk#2]
Hi, can you please provide an example of how to create table relations in code?

**Comment by makosovic** [comment]
At this moment SchemaBuilder does not support relationship building, however you can create the schema object yourself.

``` csharp
TableSchema staffSchema = new TableSchema();
staffSchema.Name = "staff";
staffSchema.Field = new List<FieldSchema>
{
// fields...
    new FieldSchema
    {
        Name = "department_id",
        Type = "reference",
        AllowNull = false,
        RefTable = "department",
        RefFields = "id"
    },
// more fields...
};

await databaseApi.CreateTableAsync(staffSchema);
```

Of course you should have the 'department' table already created, otherwise you will get an exception.

Hope this resolves you issue.
Regards
Marko
