### ISSUE TITLE
errors when using the dbapi and a mongo db database service

### ISSUE THREAD

**Issue by egarim** [dreamfactorysoftware/.net-sdk#20]
Hi Marko
in the .net sdk example I change the database demo to use mongodb service instead of db, the example run almost perfect but the delete and update operations are not working, I guess is more a problem of the rest api ,than the sdk. I will post this on the community as well, let me know if there is a way around this 2 problems in the .net sdk

error when deleting an object
500 - Failed to delete records from 'staff'.
Array to string conversion

error when updating an object

400 - Required id field(s) not found in record 0: Array
(
    [Uid] =&gt; 0
    [FirstName] =&gt; Andrei 2
    [LastName] =&gt; Smirnov
    [Age] =&gt; 35
    [Active] =&gt; 1
)

**Comment by makosovic** [comment]
Hi, I'll look into it tomorrow and let you know.

Regards
Marko

**Comment by makosovic** [comment]
At first glance it seems that field _id that mongo uses as primary key for every document is an issue. Because it is not included in poco and therefore not sent to the server. I'll look into it furter and keep you posted. Have you perhaps been working on it any more?

**Comment by egarim** [comment]
Hi Mark well I was trying to test how db api works with nosql, since the db api does not support transactions I was thinking  on move my development no nosql since is more transportable for master detail scenarios

**Comment by makosovic** [comment]
Found a solution: 

When working with mongo every POCO will have to have following property.

``` csharp
public string _id { get; set; }
```

You can put it in a MongoEntity base class and derive all other POCO from that class.

Regards
Marko
