### ISSUE TITLE
is there a way to create common table rules such as field unique, field required using the IDatabaseApi?

### ISSUE THREAD

**Issue by egarim** [dreamfactorysoftware/.net-sdk#3]
is there a way to create common table rules such as field unique, field required using the IDatabaseApi?

**Comment by egarim** [comment]
I guess I should use the FieldSchema class and the Validation  property to do the validations, any example on how to use this field?

**Comment by makosovic** [comment]
Exactly, I'm working on a hotfix at this moment regarding Validation it will no longer be a collection of string but an anonymous object. You will be able to use it as following

``` csharp
FieldSchema schema = new FieldSchema {
   Name = "Website",
   Validation = new {
      url = new {
         on_fail = "Invalid url!" 
      }
   }
}
```

You can expect the hotfix to be merged into the master branch in a couple of hours. 
Regards 
Marko

**Comment by egarim** [comment]
Great Marko when its done I'm going to do a youtube video on how to use it

**Comment by makosovic** [comment]
Excellent, I'll make sure to notify you when I'm done.

**Comment by makosovic** [comment]
I have released the hotfix so you can try define the validation now from code. I will go ahead and close this issue. Feel free to let me know if you run into any other problems.

Regards
Marko

**Comment by egarim** [comment]
Hi Marko 
I ran the code and it worked at least it ran without errors, is there a way I can double check if the validation is created? it does not seam to create anything at database level, maybe the validation live only on the df metadata?

**Comment by makosovic** [comment]
Of course, you can call `DescribeTableAsync` or `DescribeFieldAsync` in the IDatabaseApi and you should see validation now in the field you have defined in on.
