### ISSUE TITLE
catch error from database

### ISSUE THREAD

**Issue by egarim** [dreamfactorysoftware/.net-sdk#4]
what would happened if an operation in the database breaks a rule (such as field unique or field required) what kind of exception will I get? I'm asking because I don't know where should I place the validations for the records on the U.I or the database level. I guess it will be better to use the database level and just handle the exception ? please advise

**Comment by makosovic** [comment]
After the hotfix merge you will be able to see your validation "on_fail" in the exception message. You will not however be able to see all validation errors but only the one that failed. For example if you have multiple validations that should fail only the first validation message will be returned. You can read up on validation here: https://github.com/dreamfactorysoftware/platform-wiki/blob/master/Platform-Documentation/REST-API/Database/Database-Schema.md#validations

Regards
Marko

**Comment by makosovic** [comment]
I didn't answer your part of the question about where should you put validation. My experience has taught me that there is never too much validation. Sometimes it is a burden to maintain validation at multiple levels and there are more than a couple of libraries that are dealing with that issue however I still believe validation is necessary in all layers. UI for user-experience, server-side for sanity and database for data quality. 

As for the validation error message you should see them now in the exception thrown by the SDK 2.0.3 release.

Regards
Marko
