### ISSUE TITLE
mongodb example

### ISSUE THREAD

**Issue by egarim** [dreamfactorysoftware/.net-sdk#6]
Hi can you please include a mongodb example ? I would like to know how to do the CRUD operations and queries using the .net sdk

**Comment by makosovic** [comment]
It should be the same as any other db service, you just create a IDatabaseApi with the MongoDb service name you've set up in the admin and use the service as you would any other database service. I assume there are some limitations but you should take a look at documentations or ask the question on the forum for more information.

Regards
Marko
