### ISSUE TITLE
Add validation to an existing schema

### ISSUE THREAD

**Issue by egarim** [dreamfactorysoftware/.net-sdk#8]
Hi I have a desktop app for which I need to create a mobile client, the desktop app have all its validation rules on the UI and non in the database. so I wonder what would happened to the schema if I add validations using dream factory? will it alter the database to add the rules I create using the SDK?

**Comment by makosovic** [comment]
It's not really an SDK question, it's more of a DB question. If drivers for your DB allow DreamFactory to alter the table and add constraint it will. However if your table already has existing data that will break the constraints you are trying to add then the alter command will fail.
