### ISSUE TITLE
generic foreign key

### ISSUE THREAD

**Issue by egarim** [dreamfactorysoftware/.net-sdk#9]
Is there a way to create classes that implement the generic foreign key pattern? using inheritance or the table builder. this is a example of what I want to do

Table task have a field name owner of type person , Internal employee and outsource employee inherits from the type person, so the table task can hold a person, a internal employee or an outsource employee in his owner field

**Comment by makosovic** [comment]
There is no convention in SDK or SchemaTableBuilder that would allow you to do that. However I would assume that you are able to do it by defining your own FieldSchema. The Person table would have an auto incremented primary key, while internal and outsource employee should have a primary key that is not auto incremented and is also a foreign key to the person table.

Regards
Marko
